import type { Metadata } from 'next';
import './globals.css';
import { type ReactNode, Suspense } from 'react';
import PageLoader from './loading';
import { montserrat } from '../styles/font';

export const metadata: Metadata = {
  title: 'Next Template',
  description: 'Generated by create next app',
  robots: 'index, follow',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <Suspense fallback={<PageLoader />}>{children}</Suspense>
      </body>
    </html>
  );
}
