name: Deploy CI
on:
  push:
    branches: ["frontend", "main"]
  pull_request:
    branches: ["frontend", "main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Setup/ Checkout
        uses: actions/checkout@v4

      - name: Setup/ Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: pnpm-lock.yaml
        working-directory: ./frontend

      - name: Setup/ Install pnpm 9.7.0 manually
        run: npm install -g pnpm@9.7.0
        working-directory: ./frontend

      - name: Setup/ Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend

      - name: Lint/ Run ESLint
        run: pnpm lint
        working-directory: ./frontend

      - name: Test/ Unit & Integration tests
        run: pnpm test
        working-directory: ./frontend

      - name: Smoke & Acceptance tests
        run: |
          pnpm prebuild:storybook
          pnpm build:storybook --quiet
          pnpm playwright install
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && pnpm test:storybook"
        working-directory: ./frontend

  deploy:
    if: ${{ success() && github.ref == 'refs/heads/frontend' }}
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Setup/ Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        working-directory: ./frontend

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend
